spring.application.name=sis-cakes-menu

# DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/siscakes_menu
spring.datasource.username=siscakes_user
spring.datasource.password=siscakes_admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=${ACTIVE_PROFILE:dev}